front:
    path: /
    controller: App\Controller\MainController::index

new:
    path: /new
    controller: App\Controller\MainController::new

newautor:
    path: /nuevoAutor
    controller: App\Controller\MainController::newAutor

autores:
    path: /autores
    controller: App\Controller\MainController::autores

edit:
    path: /edit/{id}
    controller: App\Controller\MainController::edit

editautor:
    path: /editAutor/{id}
    controller: App\Controller\MainController::editAutor
    
remove:
    path: /remove/{id}
    controller: App\Controller\MainController::remove