index:
    path: /
    controller: App\Controller\AtomoController::index
    
page:
    path: /{route}.html
    controller: App\Controller\AtomoController::index
    
blog:
    path: /blog
    controller: App\Controller\AtomoController::blog
    
projects:
    path: /my-projects
    controller: App\Controller\AtomoController::projects
    
project:
    path: /my-projects/{route}.html
    controller: App\Controller\AtomoController::project
    
contact:
    path: /contact
    controller: App\Controller\AtomoController::contact
    
contact2:
    path: /free-consultation
    controller: App\Controller\AtomoController::contact
   
post:
    path: /blog/{route}.html
    controller: App\Controller\AtomoController::post
    
backend:
    path: /backend
    controller: App\Controller\BackendController::Index
    
login:
    path: /login
    controller: App\Controller\BackendController::Login
    
logout:
    path: /logout
    controller: App\Controller\BackendController::Logout
    
backend_pages:
    path: /backend/pages
    controller: App\Controller\BackendController::Pages
    
backend_page_add:
    path: /backend/pages/add
    controller: App\Controller\BackendController::PageAdd
    
backend_page_edit:
    path: /backend/pages/edit/{uuid}
    controller: App\Controller\BackendController::PageEdit
    
backend_page_remove:
    path: /backend/pages/remove/{uuid}
    controller: App\Controller\BackendController::PageRemove
    
backend_posts:
    path: /backend/posts
    controller: App\Controller\BackendController::Posts
    
backend_post_add:
    path: /backend/posts/add
    controller: App\Controller\BackendController::PostAdd
    
backend_post_edit:
    path: /backend/posts/edit/{uuid}
    controller: App\Controller\BackendController::PostEdit
    
backend_post_remove:
    path: /backend/posts/remove/{uuid}
    controller: App\Controller\BackendController::PostRemove
    
backend_projects:
    path: /backend/projects
    controller: App\Controller\BackendController::Projects
    
backend_project_add:
    path: /backend/projects/add
    controller: App\Controller\BackendController::ProjectAdd
    
backend_project_edit:
    path: /backend/projects/edit/{uuid}
    controller: App\Controller\BackendController::ProjectEdit
    
backend_project_remove:
    path: /backend/projects/remove/{uuid}
    controller: App\Controller\BackendController::ProjectRemove
    
backend_messages:
    path: /backend/messages
    controller: App\Controller\BackendController::Messages
    
backend_users:
    path: /backend/users
    controller: App\Controller\BackendController::users
    
backend_user_add:
    path: /backend/users/add
    controller: App\Controller\BackendController::userAdd
    
backend_user_edit:
    path: /backend/users/edit/{uuid}
    controller: App\Controller\BackendController::userEdit
    
backend_user_remove:
    path: /backend/users/remove/{uuid}
    controller: App\Controller\BackendController::userRemove

